USE DATABASE SPLITPAL;
CREATE TABLE IF NOT EXISTS CREDENTIALS (
    id uuid PRIMARY KEY,
    hashed_password TEXT NOT NULL,
    user_id uuid NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
);