USE DATABASE SPLITPAL;
CREATE TABLE IF NOT EXISTS GROUPS (
    id uuid PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    owner_id uuid NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (owner_id) REFERENCES USERS(id) ON DELETE RESTRICT
);