USE DATABASE SPLITPAL;
CREATE TABLE IF NOT EXISTS GROUPS (
    id uuid PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    owner_id uuid UNIQUE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES USERS(id),
    CONSTRAINT GROUP_UNIQUE_PAIR UNIQUE(id, owner_id)
);