USE DATABASE SPLITPAL;
CREATE TABLE IF NOT EXISTS CREDENTIALS (
    id uuid PRIMARY KEY,
    hashed_password TEXT NOT NULL,
    user_id uuid UNIQUE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USERS(id),
	CONSTRAINT UNIQUE_PAIR UNIQUE(id, user_id)
);