USE DATABASE SPLITPAL;
CREATE TABLE IF NOT EXISTS USERS (
    id uuid PRIMARY KEY,
    fname TEXT NOT NULL,
    lname TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX email_index ON USERS(email);