USE DATABASE SPLITPAL;
CREATE TABLE IF NOT EXISTS GROUP_MEMBERS (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL,
    group_id uuid NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), 
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES GROUPS(id) ON DELETE CASCADE,
    CONSTRAINT GROUP_MEMBERS_UNIQUE_PAIR UNIQUE(group_id, user_id)
);

CREATE INDEX IF NOT EXISTS index_group_member_group ON GROUP_MEMBERS(group_id);
CREATE INDEX IF NOT EXISTS index_group_member_user ON GROUP_MEMBERS(user_id);